name: Docker build
on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: eyyuperdogan/rabbitmqsendingmail@master
        with:
          image: eyyuperdogan/rabbitmqsendingmail
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          cache_registry: eyyuperdogan/rabbitmqsendingmail
